# Generated by Django 4.2 on 2023-06-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_working', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='終了時間')),
                ('start_overtime', models.CharField(max_length=20, null=True)),
                ('end_overtime', models.CharField(max_length=20, null=True)),
                ('is_sending', models.BooleanField(default=False)),
                ('staff_drink', models.IntegerField(default=0)),
                ('staff_bottle', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('how_cash', models.CharField(max_length=20, null=True)),
                ('asign', models.BooleanField(default=False)),
                ('client_name', models.CharField(max_length=20, null=True)),
                ('client_num', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(verbose_name='来店時間')),
                ('end_time', models.DateTimeField(verbose_name='退店時間')),
                ('start_overtime', models.CharField(max_length=20, null=True)),
                ('end_overtime', models.CharField(max_length=20, null=True)),
                ('memo_str', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SheetAccountRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=3, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.account')),
                ('checksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.checksheet')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_ID', models.CharField(max_length=10, null=True)),
                ('attr', models.CharField(max_length=3, null=True)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('is_use', models.BooleanField(default=False)),
                ('CheckSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.checksheet')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, null=True)),
                ('staff', models.CharField(max_length=20, null=True)),
                ('item_num', models.IntegerField()),
                ('item_cost', models.IntegerField()),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.itemmenu')),
                ('checkSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.checksheet')),
            ],
        ),
        migrations.AddField(
            model_name='checksheet',
            name='staff',
            field=models.ManyToManyField(through='attendance.SheetAccountRelation', to='attendance.account'),
        ),
    ]
