# Generated by Django 4.2 on 2023-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksheet',
            name='staff',
            field=models.ManyToManyField(related_name='staff', through='attendance.SheetAccountRelation', to='attendance.account'),
        ),
    ]
