# Generated by Django 4.2 on 2023-04-16 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
        ),
    ]
