# Generated by Django 4.2 on 2023-05-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_checksheet_memo_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_y',
            field=models.IntegerField(default=0),
        ),
    ]
