# Generated by Django 4.2 on 2023-06-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_checksheet_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksheet',
            name='staff',
            field=models.ManyToManyField(through='attendance.SheetAccountRelation', to='attendance.account'),
        ),
        migrations.CreateModel(
            name='SheetStaffRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.IntegerField(default=0)),
                ('bottle', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.account')),
                ('checksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.checksheet')),
            ],
        ),
        migrations.AddField(
            model_name='checksheet',
            name='drink_staff',
            field=models.ManyToManyField(related_name='drink', through='attendance.SheetStaffRelation', to='attendance.account'),
        ),
    ]
