# Generated by Django 4.2 on 2023-04-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='end_time',
            field=models.DateTimeField(verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_time',
            field=models.DateTimeField(verbose_name='開始時間'),
        ),
    ]
