# Generated by Django 4.2 on 2023-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_checksheet_staff_sheetstaffrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='back',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
