# Generated by Django 4.2 on 2023-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_account_back_account_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetaccountrelation',
            name='back',
            field=models.IntegerField(default=0),
        ),
    ]
