# Generated by Django 4.2 on 2023-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_account_end_time_alter_account_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
