# Generated by Django 4.2 on 2023-04-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_delete_usercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='end_overtime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='start_overtime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
