# Generated by Django 4.2 on 2023-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_account_end_overtime_account_start_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_sending',
            field=models.BooleanField(default=False),
        ),
    ]
