# Generated by Django 4.2 on 2023-05-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_seat_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='staff_bottle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='staff_drink',
            field=models.IntegerField(default=0),
        ),
    ]
