# Generated by Django 4.2 on 2023-06-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_account_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetaccountrelation',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
    ]
