# Generated by Django 4.2 on 2023-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_account_staff_bottle_account_staff_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='staff',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
